from typing import Protocol
from iam.domain.model.aggregates.User import User, UserRole


class UserRepository(Protocol):

    async def save(self, user: User) -> User: ...
    async def find_by_id(self, user_id: int) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def find_by_username_or_email(self, username_or_email: str) -> User | None: ...
    async def find_all(
        self,
        role: UserRole | None = None,
        is_active: bool | None = None,
        suspended_only: bool = False,
    ) -> list[User]: ...
    async def delete(self, user: User) -> None: ...
    async def exists_by_username(self, username: str) -> bool: ...
    async def exists_by_email(self, email: str) -> bool: ...